syntax = "proto3";
package CARTA;

import "defs.proto";
import "enums.proto";

// Data stream for Render3D cube
message Render3DData {
    // ID for the Render3D viewer
    sfixed32 viewer_id = 1;
    // Image extended file info
    FileInfoExtended image_info = 2;
    // Image data. For uncompressed data, this is converted into FP32, while for compressed data,
    // this is passed to the compression library for decompression.
    bytes image_data = 3;
    // SubImage with (partial) slices of the 3D cube
    repeated SubImage slices = 5;
    // Run-length encodings of NaN values used to restore the NaN values after decompression.
    bytes nan_encodings = 4;
    // Dimensions of data
    sfixed32 width = 5;
    sfixed32 height = 6;
    sfixed32 depth = 7;
    // The compression algorithm used
    CompressionType compression_type = 8;
    // Compression quality switch
    float compression_quality = 9;
    // Progress indicator, in the case of partial SubImage being sent. If there are many SubImages to be sent,
    // time-consuming, regular updates should be sent to the frontend. If the data is complete, progress >= 1.
    float progress = 10;
}
