syntax = "proto3";
package CARTA;

import "defs.proto";
import "enums.proto";

// Data stream for Render3D cube
message Render3DData {
    // ID for the Render3D viewer
    sfixed32 viewer_id = 1;
    // Image data. For uncompressed data, this is converted into FP32, while for compressed data,
    // this is passed to the compression library for decompression.
    bytes image_data = 2;
    // Run-length encodings of NaN values used to restore the NaN values after decompression.
    bytes nan_encodings = 3;
    // Dimensions of data
    sfixed32 width = 4;
    sfixed32 height = 5;
    sfixed32 depth = 6;
    // The compression algorithm used
    CompressionType compression_type = 7;
    // Compression quality switch
    float compression_quality = 8;
    // Progress indicator, in the case of partial data being sent.
    // Time-consuming, regular updates should be sent to the frontend. If the data is complete, progress >= 1.
    float progress = 9;
}
